name: multi_tool
# either manually started, or on a schedule
on: [ push ]
jobs:
  multi_tool:
    env:
        OPENLANE_ROOT:  /home/runner/openlane
        PDK_ROOT:       /home/runner/pdk
        PDK:            sky130B
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v2

    # install oss fpga tools
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v1
      with:
        osscadsuite-version: '2022-09-03' # pin the version, latest one fails to work with caravel : https://github.com/mattvenn/wrapped_rgb_mixer/actions/runs/3696349424/jobs/6259927750#step:20:35
    - run: | 
        yosys --version
        iverilog -V
        cocotb-config --libpython
        cocotb-config --python-bin

    # need python
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt

    # pwd
    - name: pwd
      run: |
        pwd # /home/runner/work/multi_project_tools/multi_project_tools
        cocotb-config --libpython
        cocotb-config --python-bin

    # build pdk
    - name: pdk & caravel
      run: |
        cd $HOME
        git clone https://github.com/efabless/caravel_user_project.git -b mpw-8c
        cd caravel_user_project
        make setup

    # run the script
    - name: fetch all
      #run: python ./multi_tool.py --clone-repos --clone-shared-repos --openram --local github_local.yaml
      run: python ./multi_tool.py --clone-repos --clone-shared-repos --local github_local.yaml

    # tests
    - name: test gds
      run: python ./multi_tool.py --test-gds --local github_local.yaml

    - name: test ports
      run: python ./multi_tool.py --test-ports --local github_local.yaml

    - name: test module
      run: python ./multi_tool.py --test-module --local github_local.yaml

    - name: prove wrapper
      run: python ./multi_tool.py --prove-wrapper --local github_local.yaml

# needs netgen
#    - name: lvs
#      run: python ./multi_tool.py --test-lvs --local github_local.yaml

# needs pdk
    - name: tristate-z
      run: python ./multi_tool.py --test-tristate-z --local github_local.yaml

    - name: docs
      run: python ./multi_tool.py --generate-doc --local github_local.yaml
